### ISSUE TITLE
Image generation is failing with an error

### ISSUE THREAD

**Issue by scottjehl** [stevelacey/netlify-screenshot#1]
Hi there! I love this little service and have been using it for a while. 

Just today I noticed that it started failing to produce an image. The following error appears for every URL, and it looks like the same error is showing for the demo links in this README as well. Maybe something changed at Netlify to make this no longer work as configured?

Thank you so much for any thoughts you have!

<img width="873" alt="image" src="https://github.com/stevelacey/netlify-screenshot/assets/214783/1c57f3b4-7f41-48bd-9c60-7691d5a37e1d">

**Comment by stevelacey** [comment]
@scottjehl hey there! I don't know that I was seeing this particular error, but I ran into a different issue a month ago and ultimately swapped over to using Cloudflare Workers instead of Netlify. I ported this code over to https://github.com/stevelacey/cloudflare-screenshot and that's the repository I'll be maintaining moving forward. Let me know if you also make the switch, and how you get on with it!
